"""Configuration constants for Topview."""

from pathlib import Path

APP_NAME = "Topview"
WINDOW_TITLE = "Topview"
DEFAULT_INFO_FONT_SIZE = 12.0
DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 800

CHARGE_SCALE = 18.2223

PACKAGE_ROOT = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_ROOT.parent
WEB_DIR = REPO_ROOT / "web"
INDEX_PATH = WEB_DIR / "index.html"
PARM7_REFERENCE_PATH = REPO_ROOT / "daux" / "src_parm7_ref.md"

PARM7_TOKEN_SECTIONS = {
    "POINTERS",
    "ATOM_NAME",
    "CHARGE",
    "ATOMIC_NUMBER",
    "MASS",
    "ATOM_TYPE_INDEX",
    "AMBER_ATOM_TYPE",
    "RESIDUE_LABEL",
    "RESIDUE_POINTER",
    "BONDS_INC_HYDROGEN",
    "BONDS_WITHOUT_HYDROGEN",
    "BOND_FORCE_CONSTANT",
    "BOND_EQUIL_VALUE",
    "ANGLES_INC_HYDROGEN",
    "ANGLES_WITHOUT_HYDROGEN",
    "ANGLE_FORCE_CONSTANT",
    "ANGLE_EQUIL_VALUE",
    "DIHEDRALS_INC_HYDROGEN",
    "DIHEDRALS_WITHOUT_HYDROGEN",
    "DIHEDRAL_FORCE_CONSTANT",
    "DIHEDRAL_PERIODICITY",
    "DIHEDRAL_PHASE",
    "SCEE_SCALE_FACTOR",
    "SCNB_SCALE_FACTOR",
    "NONBONDED_PARM_INDEX",
    "LENNARD_JONES_ACOEF",
    "LENNARD_JONES_BCOEF",
    "HBOND_ACOEF",
    "HBOND_BCOEF",
    "HBCUT",
}
