import { DEFAULT_SELECTION_MODE, DEFAULT_STYLE_KEY } from "./constants.js";

export const state = {
  viewer: null,
  viewMode: "3d",
  model: null,
  baseStyle: null,
  currentSelection: [],
  loading: false,
  currentStyleKey: DEFAULT_STYLE_KEY,
  pywebviewReady: false,
  pendingLoad: null,
  systemInfo: null,
  systemInfoVisible: true,
  systemInfoTab: DEFAULT_SELECTION_MODE,
  systemInfoHighlight: null,
  systemInfoRowCursor: new Map(),
  systemInfoSort: null,
  threeDmolPromise: null,
  parm7Lines: [],
  parm7Sections: [],
  parm7LineNodes: new Map(),
  parm7HighlightsByLine: new Map(),
  parm7LinesContainer: null,
  parm7Spacer: null,
  parm7LineHeight: 16,
  parm7Window: { start: 0, end: 0 },
  parm7ScrollAttached: false,
  parm7ScrollScheduled: false,
  parm7ViewIndices: null,
  parm7ViewIndexMap: null,
  sectionTooltip: null,
  zoomHandlerAttached: false,
  currentAtomInfo: null,
  aboutVisible: false,
  darkMode: true,
  eventsAttached: false,
  currentInteraction: null,
  atomCache: new Map(),
  renderScheduled: false,
  renderPending: false,
  selectionSource: "viewer",
  selectionNonce: 0,
  selectionSerials: [],
  selectionMode: DEFAULT_SELECTION_MODE,
  atomBySerial: new Map(),
  atomIndexBySerial: new Map(),
  atomByIndex: new Map(),
  modelAtoms: [],
  rdkitSvgNode: null,
  rdkitOverlayNode: null,
  rdkitAtomSerials: [],
  rdkitAtomIndexBySerial: new Map(),
  rdkitAtomCoords: [],
  rdkitAtomNames: [],
  rdkitBondPairs: [],
  rdkitBondIndexByPair: new Map(),
  rdkitClickHandler: null,
  viewerLabelNodes: [],
  emptyClickArmed: false,
  emptyClickArmed2d: false,
  lastAtomClick: false,
};
